version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  quizcraft:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/quizcraft
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /quizcraft/log
      - /quizcraft/tmp
      - vendor_bundle:/quizcraft/vendor/bundle
      - node_modules:/quizcraft/node_modules
      - storage:/quizcraft/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - default

  chrome:
    image: selenium/standalone-chrome:114.0
    ports:
      - "4444:4444"
