version: "3"
volumes:
  mysql_data:
  vendor_bundle:
  node_modules:
  storage:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  quizcraft:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
      GOOGLE_CLIENT_ID: "1084132138336-m0p9ujbhvdqf72cd5ko7fen9ck2qaiv1.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      FACEBOOK_APP_ID: "1105642750504524"
      FACEBOOK_APP_SECRET: "f64ae77d587ba3bd65358276a79fe29b"
      GOOGLE_APPLICATION_CREDENTIALS: "/quizcraft/service-account-key.json"
      OPENAI_API_KEY: "sk-quizcraft-key-vzBwcyaOZwXuVEKigI6iT3BlbkFJC4gpVg6GNDEajux6lt6J"
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/quizcraft
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /quizcraft/log
      - /quizcraft/tmp
      - vendor_bundle:/quizcraft/vendor/bundle
      - node_modules:/quizcraft/node_modules
      - storage:/quizcraft/storage
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - default

  chrome:
    image: selenium/standalone-chrome:114.0
    ports:
      - "4444:4444"
