version: "3"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default
    ports:
      - '33306:3306'
    command: --default-authentication-plugin=mysql_native_password

  quizcraft:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mysql
    networks:
      - default
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0

  chrome:
    image: selenium/standalone-chrome:114.0
    ports:
      - "4444:4444"
    networks:
      - default
