version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2
  heroku: circleci/heroku@1.2.2  # Heroku Orbを追加

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-v1-{{ checksum "Gemfile.lock" }}
      - ruby/install-deps

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.3.4-node
    steps:
      - setup_remote_docker
      - setup
      - run:
          name: Build and run services with docker-compose
          command: |
            docker-compose -f docker-compose.ci.yml up -d
            docker-compose ps
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 60`; do
              docker-compose exec mysql mysqladmin ping -u root -ppassword --silent && break;
              echo "Waiting for MySQL... $i";
              sleep 3;
            done
            docker-compose ps
      - run:
          name: Rspec
          command: docker-compose exec quizcraft bundle exec rspec
      - run:
          name: Rubocop
          command: bundle exec rubocop --parallel

  deploy_to_heroku:
    docker:
      - image: cimg/ruby:3.3.4-node
    steps:
      - setup_remote_docker
      - run:
          name: Heroku Login
          command: heroku container:login
      - run:
          name: Set Heroku Stack
          command: heroku stack:set container -a quiz-craft
      - run:
          name: Build Docker Image
          command: docker build -t quiz-craft -f Dockerfile.prod .
      - run:
          name: Tag Docker Image
          command: docker tag quiz-craft registry.heroku.com/quiz-craft/web
      - run:
          name: Push Docker Image to Heroku
          command: docker push registry.heroku.com/quiz-craft/web
      - run:
          name: Release to Heroku
          command: heroku container:release web --app quiz-craft
      - run:
          name: Migrate Database
          command: heroku run rails db:migrate --app quiz-craft
      - run:
          name: Seed Database
          command: heroku run rails db:seed --app quiz-craft
      - run:
          name: Restart Heroku App
          command: heroku restart --app quiz-craft

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy_to_heroku:
          requires:
            - build_and_test
